### PR TITLE
Re-added "os" import

### PR DESCRIPTION
**Pull request by wonderb0lt**
Hey everyone,

I've been following the python example along, and ran into trouble:

```
$ sudo docker run --link redis:redis -p 5000:5000 -ti --rm registry.giantswarm.io/wonderb0lt/currentweather                          

Traceback (most recent call last):
  File "server.py", line 8, in <module>
    "CACHE_REDIS_HOST": os.getenv("REDIS_PORT_6379_TCP_ADDR"),
```

I've re-added the "os" import and everything is working fine:

```
$ sudo docker run --link redis:redis -p 5000:5000 -ti --rm registry.giantswarm.io/wonderb0lt/currentweather  

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

### CODE REVIEW

**Comment by marians** [comment]
@wonderb0lt Thanks so much for the notice! That was my fault.

I have fixed the problem in a different way here: https://github.com/giantswarm/giantswarm-firstapp-python/commit/b2c5da9767b2bad7ba852ea332845cd05757a822

**Comment by wonderb0lt** [comment]
I think it's a better example if you see "Look, there's environment variables!" but in the end, you're the one maintaining it :)

**Comment by marians** [comment]
When these env variables aren't really needed, it's much cleaner without IMHO. The fact that "redis" resolves to the right IP address as long as the name is set correct in `swarm.json` probably needs some more mentioning in our docs pages though.

**Comment by wonderb0lt** [comment]
Fair enough. Alright, then, let's close the PR then.

**Pull request closed without merging**
